function relay_code_number()
   
    relay_codes = containers.Map( ...
        {'50', '51', '27', '59', '87', '32', '21'}, ...
        {'Instantaneous Overcurrent', ...
         'Time-Delayed Overcurrent', ...
         'Undervoltage', ...
         'Overvoltage', ...
         'Differential Protection', ...
         'Directional Power', ...
         'Distance Protection'} ...
    );

    
    relay_code = input('Enter ANSI relay code: ', 's');

    if isKey(relay_codes, relay_code)
        fprintf('ANSI Code %s: %s\n', relay_code, relay_codes(relay_code));
    else
        fprintf('ANSI Code %s not found in database.\n', relay_code);
    end
end
